# Generated by Django 6.0.7 on 2026-10-01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0005_commissionrequest_subject_commissionrequest_style"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotification",
            name="commission",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="commissions.commissionrequest"),
        ),
    ]
