# Generated by Django 6.0.7 on 2026-09-19 19:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_alter_user_role'),
        ('wallets', '0002_paymentsession_agreement_cancellationreturnrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_city', models.CharField(max_length=150)),
                ('destination_city', models.CharField(max_length=150)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('base_fare', models.DecimalField(decimal_places=2, default=50, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('per_km', models.DecimalField(decimal_places=2, default=15, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Awaiting rider'), ('accepted', 'Rider assigned'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_order', to='wallets.paymentsession')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('artwork_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='wallets.paymentsession')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('artist_rating__gte', 1), ('artist_rating__lte', 5)), name='valid_artist_rating'), models.CheckConstraint(condition=models.Q(('artwork_rating__gte', 1), ('artwork_rating__lte', 5)), name='valid_artwork_rating')],
            },
        ),
    ]
