# Generated by Django 6.0.7 on 2026-09-21 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0001_initial'),
        ('users', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_proof',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='pickup_proof',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='timeline',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting rider'), ('accepted', 'Rider assigned'), ('arrived_at_artist', 'Arrived at artist'), ('picked_up', 'Artwork collected'), ('arrived_at_buyer', 'Arrived at buyer'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_clocked_in', models.BooleanField(default=False)),
                ('clock_in_time', models.DateTimeField(blank=True, null=True)),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to='users.user')),
            ],
        ),
    ]
