# Generated by Django 6.0.7 on 2026-09-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0002_deliveryorder_delivery_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereview',
            name='artist_comment',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='purchasereview',
            name='artwork_comment',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
