# Generated by Django 6.0.7 on 2026-09-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='artist_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='artist_name',
            field=models.CharField(blank=True, default='Artist Studio', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='artist_phone',
            field=models.CharField(blank=True, default='09987654321', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_phone',
            field=models.CharField(blank=True, default='09123456789', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=125.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_proof',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='distance_km',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='order',
            name='instructions',
            field=models.TextField(blank=True, default='Handle with care.'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='item_name',
            field=models.CharField(default='Artwork Asset', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_address',
            field=models.CharField(default='Cebu City Art Studio', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_proof',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='distance',
            field=models.CharField(default='5.0 km', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimatedTime',
            field=models.CharField(default='25 mins', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('PAYPAL', 'Paypal'), ('AUCTION_WIN', 'Auction Win')], default='COD', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Request'), ('ACCEPTED', 'Accepted'), ('ARRIVED_AT_ARTIST', 'Arrived at Artist'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED_AT_BUYER', 'Arrived at Buyer'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Cancelled')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='phone',
            field=models.CharField(default='09123456789', max_length=20),
        ),
    ]
