# Generated by Django 6.0.7 on 2026-09-24 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_order_artist_id_order_artist_name_order_artist_phone_and_more'),
        ('wallets', '0004_paymentsession_is_simulated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='artist_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='order',
            name='instructions',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_latitude',
            field=models.FloatField(default=10.3333),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_longitude',
            field=models.FloatField(default=123.9333),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='wallets.paymentsession'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_latitude',
            field=models.FloatField(default=10.3157),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_longitude',
            field=models.FloatField(default=123.8854),
        ),
        migrations.AlterField(
            model_name='order',
            name='artist_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='artist_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='distance',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimatedTime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(default='PAYPAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
