# Generated by Django 6.0.7 on 2026-09-24 15:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRequest',
            fields=[
                ('commission_req_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_duration', models.DecimalField(decimal_places=2, help_text='Agreed total price / duration', max_digits=12)),
                ('type', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In-progress'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('is_rush_job', models.CharField(choices=[('EXCLUSIVE', 'Exclusive'), ('NON_EXCLUSIVE', 'Non-exclusive'), ('SOLE', 'Sole')], default='NON_EXCLUSIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In-progress'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_commissions', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_commissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionPhoto',
            fields=[
                ('photo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='commissions/')),
                ('image_url', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('commission_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='commissions.commissionrequest')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionMilestone',
            fields=[
                ('milestone_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('milestone_number', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('percentage', models.IntegerField(help_text='Percentage of total amount')),
                ('amount', models.IntegerField(help_text='Amount of transaction')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('commission_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='commissions.commissionrequest')),
            ],
        ),
    ]
