# Generated by Django 6.0.7 on 2026-09-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionphoto',
            name='image',
        ),
        migrations.RemoveField(
            model_name='commissionrequest',
            name='type',
        ),
        migrations.AddField(
            model_name='commissionphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commissionphoto',
            name='photo_type',
            field=models.CharField(choices=[('REFERENCE', 'Reference (Buyer)'), ('PROGRESS', 'Progress Track (Artist)')], default='REFERENCE', max_length=20),
        ),
        migrations.AddField(
            model_name='commissionphoto',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commissionrequest',
            name='art_type',
            field=models.CharField(default='Physical', max_length=20),
        ),
        migrations.AddField(
            model_name='commissionrequest',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commissionmilestone',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commissionmilestone',
            name='percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commissionmilestone',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='commissionphoto',
            name='image_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commissionrequest',
            name='is_rush_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commissionrequest',
            name='time_duration',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
