# Generated by Django 6.0.7 on 2026-09-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_remove_commissionphoto_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionmilestone',
            name='stage_label',
            field=models.CharField(default='Stage 1', max_length=50),
        ),
        migrations.AddField(
            model_name='commissionphoto',
            name='stage_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='commissionrequest',
            name='cancel_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissionrequest',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commissionrequest',
            name='cancelled_at_stage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissionrequest',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='commissionmilestone',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='commissionmilestone',
            name='milestone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commissionphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commissionphoto',
            name='progress_percentage',
            field=models.IntegerField(default=33),
        ),
        migrations.AlterField(
            model_name='commissionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Artist Acceptance'), ('IN_PROGRESS', 'In Progress / Negotiating'), ('STAGE_1', 'Stage 1 (Sketch / Initial)'), ('STAGE_2', 'Stage 2 (Rendering / Detailing)'), ('STAGE_3', 'Stage 3 (Final Revision)'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
