# Generated by Django 6.0.7 on 2026-09-30 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_commissionmilestone_stage_label_and_more'),
        ('users', '0016_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionrequest',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_commissions', to='users.user'),
        ),
        migrations.AlterField(
            model_name='commissionrequest',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_commissions', to='users.user'),
        ),
    ]
