# Generated by Django 6.0.7 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0004_alter_commissionrequest_artist_and_more"),
    ]

    operations = [
        migrations.AddField(model_name="commissionrequest", name="subject", field=models.CharField(blank=True, default="", max_length=200)),
        migrations.AddField(model_name="commissionrequest", name="style", field=models.CharField(blank=True, default="", max_length=80)),
    ]
