# Generated by Django 6.0.7 on 2026-10-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_alter_commissionrequest_artist_and_more'),
        ('commissions', '0005_commissionrequest_subject_commissionrequest_style'),
    ]

    operations = [
    ]
