# Generated by Django 6.0.7 on 2026-09-18 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0006_artwork_edge_hash_artworksimilaritymatch_edge_hash_distance'),
        ('users', '0010_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='users.user')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.artwork')),
            ],
            options={
                'db_table': 'cart_item',
                'constraints': [models.UniqueConstraint(fields=('cart', 'listing'), name='unique_cart_listing'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='cart_quantity_positive')],
            },
        ),
    ]
