# Generated by Django 6.0.7 on 2026-10-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistapplication',
            name='bir_certificate_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='sworn_declaration_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='artistapplication',
            name='bir_certificate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artistapplication',
            name='sworn_declaration',
            field=models.TextField(),
        ),
    ]
