# Generated by Django 6.0.7 on 2026-08-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='sha256_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hex digest of the uploaded image, for exact-duplicate detection.', max_length=64, null=True, unique=True),
        ),
    ]
