# Generated by Django 6.0.7 on 2026-08-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_artwork_sha256_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='perceptual_hash',
            field=models.CharField(blank=True, help_text='Perceptual hash used for visually similar image detection.', max_length=64, null=True),
        ),
    ]
