# Generated by hand for ArtFiliere's internal similarity-review workflow.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0003_artwork_perceptual_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="difference_hash",
            field=models.CharField(blank=True, help_text="Difference hash used alongside pHash for visual similarity detection.", max_length=64, null=True),
        ),
        migrations.CreateModel(
            name="ArtworkSimilarityMatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phash_distance", models.PositiveSmallIntegerField()),
                ("dhash_distance", models.PositiveSmallIntegerField()),
                ("feature_match_score", models.FloatField(default=0)),
                ("confidence_score", models.FloatField()),
                ("review_status", models.CharField(choices=[("pending", "Pending review"), ("confirmed_copy", "Confirmed copy"), ("not_a_copy", "Not a copy")], default="pending", max_length=20)),
                ("review_note", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("artwork", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="similarity_matches", to="artworks.artwork")),
                ("reference_artwork", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="referenced_by_similarity_matches", to="artworks.artwork")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_similarity_matches", to="users.user")),
            ],
            options={"ordering": ["-confidence_score", "-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="artworksimilaritymatch",
            constraint=models.UniqueConstraint(fields=("artwork", "reference_artwork"), name="unique_artwork_similarity_match"),
        ),
    ]
