# Generated by Django 6.0.7 on 2026-09-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_artwork_edge_hash_artworksimilaritymatch_edge_hash_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='art_type',
            field=models.CharField(default='digital', max_length=10),
        ),
        migrations.AddField(
            model_name='artwork',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='material_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
