# Generated by Django 6.0.7 on 2026-09-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_artwork_edge_hash_artworksimilaritymatch_edge_hash_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='bid_increment',
            field=models.DecimalField(blank=True, decimal_places=2, default=100.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='sale_type',
            field=models.CharField(default='DIRECT', max_length=50),
        ),
        migrations.AddField(
            model_name='artwork',
            name='starting_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
