# Generated by Django 6.0.7 on 2026-09-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_artwork_art_type_artwork_hourly_rate_artwork_hours_and_more'),
        ('artworks', '0007_artwork_bid_increment_artwork_end_time_and_more'),
    ]

    operations = [
    ]
