# Generated by Django 6.0.7 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0008_merge_20260923_2143"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
