# Generated by Django 6.0.7 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0009_artwork_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="additional_images",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
