# Generated by Django 6.0.7 on 2026-10-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0009_artwork_medium'),
        ('artworks', '0010_artwork_additional_images'),
    ]

    operations = [
    ]
