# Generated by Django 6.0.7 on 2026-10-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0011_merge_20261002_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='medium',
        ),
    ]
