# Generated by Django 6.0.7 on 2026-09-18 14:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0006_artwork_edge_hash_artworksimilaritymatch_edge_hash_distance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_bid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bid_increment', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('is_physical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_auctions', to=settings.AUTH_USER_MODEL)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_listings', to='artworks.artwork')),
                ('highest_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_bids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionlisting')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-amount', '-created_at'],
            },
        ),
    ]
