# Generated by Django 6.0.7 on 2026-09-29 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlisting_artist'),
        ('users', '0016_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_listings', to='users.user'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_bids', to='users.user'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('ACTIVE', 'Active'), ('SCHEDULED', 'Scheduled'), ('ENDED', 'Ended'), ('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_bids', to='users.user'),
        ),
    ]
