# Generated by Django 6.0.7 on 2026-10-01 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_artist_and_more'),
        ('users', '0014_remove_user_commission_budget_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='backup_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_auction_offers', to='users.user'),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='backup_offer_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='delivery_type',
            field=models.CharField(default='digital', max_length=30),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='exclusivity',
            field=models.CharField(default='non_exclusive', max_length=30),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='license_type',
            field=models.CharField(default='personal', max_length=30),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='terms_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='winner_forfeited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='winning_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('ACTIVE', 'Active'), ('SCHEDULED', 'Scheduled'), ('ENDED', 'Ended'), ('SETTLED', 'Settled'), ('PAYMENT_PENDING', 'Winner Payment Pending'), ('BACKUP_OFFER', 'Runner-up Offer Pending'), ('FORFEITED', 'Winner Forfeited'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
    ]
