# Generated by Django 6.0.7 on 2026-10-01 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlisting_backup_bidder_and_more'),
        ('messaging', '0008_agreement_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='agreement_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_listings', to='messaging.agreementtemplate'),
        ),
    ]
