# Generated by Django 6.0.7 on 2026-10-02 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionlisting_artist'),
        ('users', '0018_merge_20261002_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_listings', to='users.user'),
        ),
    ]
