# Generated by Django 6.0.7 on 2026-10-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlisting_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='artist_signature',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='artist_signature_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='artist_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='signed_document',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='signed_document_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
