import { auth } from '@/firebase/config';
import API_URL from '@/services/api';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { ArrowLeft, MessageCircle } from 'lucide-react-native';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Image, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

export default function ArtistProfileScreen(){const {artistId}=useLocalSearchParams<{artistId:string}>();const router=useRouter();const [artist,setArtist]=useState<any>(null);const [loading,setLoading]=useState(true);useEffect(()=>{(async()=>{try{const r=await fetch(`${API_URL}/api/users/artists/${artistId}/`);const d=await r.json();if(!r.ok)throw new Error(d.error);setArtist(d);}catch(e:any){Alert.alert('Artist profile',e.message||'Unable to load this artist.');}finally{setLoading(false);}})();},[artistId]);if(loading)return <View style={s.center}><ActivityIndicator color="#C15656"/></View>;if(!artist)return <View style={s.center}><Text>Artist not found.</Text></View>;return <SafeAreaView style={s.page}><View style={s.top}><TouchableOpacity onPress={()=>router.back()}><ArrowLeft color="#fff" size={24}/></TouchableOpacity><Text style={s.name}>{artist.name}</Text><TouchableOpacity style={s.message} onPress={()=>router.push({pathname:'/messages',params:{artistId:String(artist.id),artistName:artist.name}})}><MessageCircle color="#fff" size={17}/><Text style={s.messageText}>Message</Text></TouchableOpacity></View><ScrollView contentContainerStyle={s.content}><Text style={s.handle}>@{artist.username}</Text><Text style={s.bio}>{artist.bio||'Independent artist on ArtFiliere.'}</Text><Text style={s.section}>Artwork for sale</Text><View style={s.grid}>{artist.artworks.map((item:any)=><View key={item.id} style={s.card}><Image source={{uri:item.image_data}} style={s.image}/><Text style={s.title}>{item.title}</Text><Text style={s.price}>₱ {item.price}</Text></View>)}</View></ScrollView></SafeAreaView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#FBF7E8'},top:{backgroundColor:'#C15656',minHeight:78,paddingHorizontal:16,flexDirection:'row',alignItems:'center',gap:14},name:{color:'#fff',fontSize:19,fontWeight:'800',flex:1},message:{flexDirection:'row',gap:5,alignItems:'center',backgroundColor:'rgba(255,255,255,.22)',paddingHorizontal:11,paddingVertical:8,borderRadius:18},messageText:{color:'#fff',fontSize:12,fontWeight:'800'},content:{padding:20,width:'100%',maxWidth:850,alignSelf:'center'},handle:{color:'#C15656',fontWeight:'800'},bio:{color:'#675954',fontSize:13,lineHeight:19,marginTop:7},section:{color:'#2B2320',fontWeight:'800',fontSize:17,marginTop:26,marginBottom:12},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},card:{width:150,backgroundColor:'#fff',borderRadius:10,overflow:'hidden',borderWidth:1,borderColor:'#E8D8D0'},image:{width:'100%',height:145},title:{color:'#3A2D2A',fontSize:12,fontWeight:'800',paddingHorizontal:9,paddingTop:8},price:{color:'#C15656',fontSize:12,fontWeight:'800',padding:9},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#FBF7E8'}});
