import { auth } from '@/firebase/config';
import API_URL from '@/services/api';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { ArrowLeft, Send } from 'lucide-react-native';
import { useEffect, useState } from 'react';
import { Alert, FlatList, SafeAreaView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
type Message={id:number;sender_id:number;body:string;created_at:string};
export default function DirectMessageScreen(){const {artistId,artistName}=useLocalSearchParams<{artistId:string;artistName:string}>();const router=useRouter();const [messages,setMessages]=useState<Message[]>([]);const [body,setBody]=useState('');const load=async()=>{try{const u=auth.currentUser;if(!u)return;const r=await fetch(`${API_URL}/api/users/messages/?recipient_id=${artistId}`,{headers:{Authorization:`Bearer ${await u.getIdToken()}`}});const d=await r.json();if(r.ok)setMessages(d);}catch{}};useEffect(()=>{load();},[artistId]);const send=async()=>{if(!body.trim())return;try{const u=auth.currentUser;if(!u)throw Error('Please log in again.');const r=await fetch(`${API_URL}/api/users/messages/`,{method:'POST',headers:{Authorization:`Bearer ${await u.getIdToken()}`,'Content-Type':'application/json'},body:JSON.stringify({recipient_id:artistId,body:body.trim()})});const d=await r.json();if(!r.ok)throw Error(d.error);setMessages(x=>[...x,d]);setBody('');}catch(e:any){Alert.alert('Message',e.message||'Unable to send message.');}};return <SafeAreaView style={s.page}><View style={s.head}><TouchableOpacity onPress={()=>router.back()}><ArrowLeft color="#C15656" size={24}/></TouchableOpacity><Text style={s.name}>{artistName||'Artist'}</Text><View style={{width:24}}/></View><FlatList data={messages} keyExtractor={x=>String(x.id)} contentContainerStyle={s.list} renderItem={({item})=><View style={[s.bubble,item.sender_id===Number(artistId)?s.received:s.sent]}><Text style={s.bubbleText}>{item.body}</Text></View>}/><View style={s.compose}><TextInput value={body} onChangeText={setBody} placeholder="Write a message..." style={s.input} multiline/><TouchableOpacity onPress={send} style={s.send}><Send size={19} color="#fff"/></TouchableOpacity></View></SafeAreaView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#FBF7E8'},head:{height:60,backgroundColor:'#fff',paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderColor:'#E8D8D0'},name:{fontSize:17,fontWeight:'800',color:'#2B2320'},list:{padding:14},bubble:{maxWidth:'78%',padding:10,borderRadius:12,marginBottom:8},received:{alignSelf:'flex-start',backgroundColor:'#fff'},sent:{alignSelf:'flex-end',backgroundColor:'#EFD7CD'},bubbleText:{color:'#3A2D2A',fontSize:13},compose:{flexDirection:'row',padding:10,backgroundColor:'#fff',borderTopWidth:1,borderColor:'#E8D8D0',alignItems:'center'},input:{flex:1,backgroundColor:'#F7EFEA',borderRadius:20,paddingHorizontal:14,paddingVertical:9,maxHeight:90,color:'#2B2320'},send:{width:38,height:38,borderRadius:19,backgroundColor:'#C15656',alignItems:'center',justifyContent:'center',marginLeft:8}});
