import { auth } from '@/firebase/config';
import API_URL from '@/services/api';
import { useFocusEffect, useRouter } from 'expo-router';
import { ArrowLeft, FileText, MessageCircle } from 'lucide-react-native';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, SafeAreaView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';

type Row={id:number;status:string;updated_at:string;other_user:{id:number;name:string;role:string}|null;last_message:string;last_message_type:string|null};
export default function MessagesInboxScreen(){const router=useRouter();const [rows,setRows]=useState<Row[]>([]);const [loading,setLoading]=useState(true);const load=useCallback(async()=>{try{setLoading(true);if(!auth.currentUser)return;const r=await fetch(`${API_URL}/api/users/conversations/`,{headers:{Authorization:`Bearer ${await auth.currentUser.getIdToken()}`}});const data=await r.json();if(!r.ok)throw Error(data.error);setRows(data);}catch(e:any){Alert.alert('Messages',e.message||'Unable to load conversations.');}finally{setLoading(false);}},[]);useFocusEffect(useCallback(()=>{load();},[load]));return <SafeAreaView style={s.page}><View style={s.head}><TouchableOpacity onPress={()=>router.back()}><ArrowLeft color="#C15656" size={24}/></TouchableOpacity><Text style={s.title}>Messages</Text><View style={{width:24}}/></View>{loading?<View style={s.center}><ActivityIndicator color="#C15656" size="large"/></View>:<FlatList data={rows} keyExtractor={x=>String(x.id)} contentContainerStyle={rows.length?s.list:s.center} ListEmptyComponent={<View style={s.empty}><MessageCircle color="#D7C7C0" size={42}/><Text style={s.emptyTitle}>No conversations yet</Text><Text style={s.emptyText}>Open an artist profile and tap Message to start one.</Text></View>} renderItem={({item})=><TouchableOpacity style={s.row} onPress={()=>router.push({pathname:'/messages',params:{conversationId:String(item.id),artistName:item.other_user?.name||'Conversation'}})}><View style={s.avatar}><Text style={s.avatarText}>{(item.other_user?.name||'?').slice(0,1).toUpperCase()}</Text></View><View style={s.copy}><View style={s.rowTop}><Text style={s.name}>{item.other_user?.name||'Conversation'}</Text><Text style={s.time}>{new Date(item.updated_at).toLocaleDateString()}</Text></View><Text numberOfLines={1} style={s.preview}>{item.last_message_type==='agreement'?'License and Agreement':item.last_message}</Text></View>{item.status==='agreed'&&<FileText size={17} color="#5D8A63"/>}</TouchableOpacity>}/>}</SafeAreaView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#FBF7E8'},head:{height:64,backgroundColor:'#fff',paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderColor:'#E8D8D0'},title:{color:'#2B2320',fontSize:19,fontWeight:'800'},center:{flexGrow:1,alignItems:'center',justifyContent:'center',padding:30},list:{padding:12},row:{backgroundColor:'#fff',borderRadius:12,padding:13,flexDirection:'row',alignItems:'center',gap:11,marginBottom:8,borderWidth:1,borderColor:'#EEE1D8'},avatar:{width:43,height:43,borderRadius:22,backgroundColor:'#EFD7CD',justifyContent:'center',alignItems:'center'},avatarText:{color:'#C15656',fontWeight:'800',fontSize:17},copy:{flex:1},rowTop:{flexDirection:'row',justifyContent:'space-between',gap:8},name:{color:'#352A27',fontSize:14,fontWeight:'800'},time:{color:'#9A8880',fontSize:10},preview:{color:'#786963',fontSize:12,marginTop:4},empty:{alignItems:'center'},emptyTitle:{fontSize:16,fontWeight:'800',color:'#4C3A35',marginTop:12},emptyText:{fontSize:12,color:'#7C6A64',marginTop:5,textAlign:'center'}});
