import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("artworks", "0006_artwork_edge_hash_artworksimilaritymatch_edge_hash_distance"), ("messaging", "0001_initial"), ("users", "0009_user_platform_admin_role")]
    operations = [
        migrations.CreateModel(name="AgreementTemplate", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120, unique=True)), ("body", models.TextField(help_text="Supports safe placeholders such as {{buyer_name}}, {{artist_name}}, {{amount}}.")), ("is_active", models.BooleanField(default=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="edited_agreement_templates", to="users.user"))]),
        migrations.CreateModel(name="Conversation", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("status", models.CharField(choices=[("open", "Open"), ("agreed", "Agreement accepted"), ("cancelled", "Cancelled"), ("completed", "Completed")], default="open", max_length=20)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("artwork", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="conversations", to="artworks.artwork"))]),
        migrations.CreateModel(name="ConversationParticipant", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("last_read_at", models.DateTimeField(blank=True, null=True)), ("joined_at", models.DateTimeField(auto_now_add=True)), ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="messaging.conversation")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="conversation_participations", to="users.user"))]),
        migrations.CreateModel(name="Agreement", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("price", models.DecimalField(decimal_places=2, max_digits=12)), ("terms_snapshot", models.TextField()), ("delivery_date", models.DateField(blank=True, null=True)), ("revision_limit", models.PositiveSmallIntegerField(default=0)), ("status", models.CharField(choices=[("proposed", "Proposed"), ("accepted", "Accepted"), ("cancelled", "Cancelled")], default="proposed", max_length=20)), ("buyer_accepted_at", models.DateTimeField(blank=True, null=True)), ("artist_accepted_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("artist", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="artist_agreements", to="users.user")), ("artwork", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="artworks.artwork")), ("buyer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="buyer_agreements", to="users.user")), ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agreements", to="messaging.conversation")), ("template", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="agreements", to="messaging.agreementtemplate"))]),
        migrations.CreateModel(name="Message", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("body", models.TextField(blank=True, default="")), ("message_type", models.CharField(choices=[("text", "Text"), ("agreement", "Agreement"), ("system", "System")], default="text", max_length=20)), ("created_at", models.DateTimeField(auto_now_add=True)), ("agreement", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="messages", to="messaging.agreement")), ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="messaging.conversation")), ("sender", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="conversation_messages", to="users.user"))], options={"ordering":["created_at"]}),
        migrations.AddConstraint(model_name="conversationparticipant", constraint=models.UniqueConstraint(fields=("conversation", "user"), name="unique_conversation_participant")),
    ]
