# Generated by Django 6.0.7 on 2026-09-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_agreement_license_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='artist_signature',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='agreement',
            name='artist_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='buyer_signature',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='agreement',
            name='buyer_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='document_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
    ]
