# Generated by Django 6.0.7 on 2026-09-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_agreement_artist_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='artist_signature_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agreement',
            name='buyer_signature_image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
