# Generated by Django 6.0.7 on 2026-09-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_agreement_artist_signature_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='delivery_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agreement',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
