# Generated by Django 6.0.7 on 2026-09-25 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_artist_and_more'),
        ('commissions', '0003_alter_commissionrequest_artist_and_more'),
        ('messaging', '0007_agreement_delivery_details_agreement_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='auctions.auctionlisting'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='commissions.commissionrequest'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='platform_fee_rate',
            field=models.DecimalField(decimal_places=4, default='0.10', max_digits=5),
        ),
        migrations.AddField(
            model_name='conversation',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='commissions.commissionrequest'),
        ),
    ]
