# Generated by Django 6.0.7 on 2026-10-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_agreement_auction_agreement_commission_and_more'),
        ('messaging', '0008_agreement_verification_code'),
    ]

    operations = [
    ]
