# Generated by Django 6.0.7 on 2026-10-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_merge_20261002_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='platform_fee_rate',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='commission',
        ),
    ]
