# Generated by Django 6.0.7 on 2026-10-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_remove_agreement_auction_remove_agreement_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='artist_presigned_document',
            field=models.TextField(blank=True, default=''),
        ),
    ]
