# Generated by Django 6.0.7 on 2026-08-19 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_artwork_messages_and_creative_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='application',
        ),
        migrations.RemoveField(
            model_name='artistapplicationlog',
            name='application',
        ),
        migrations.RemoveField(
            model_name='artistapplicationlog',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artworkreviewlog',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='artworkreviewlog',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='ArtistApplication',
        ),
        migrations.DeleteModel(
            name='ArtistApplicationLog',
        ),
        migrations.DeleteModel(
            name='Artwork',
        ),
        migrations.DeleteModel(
            name='ArtworkReviewLog',
        ),
        migrations.DeleteModel(
            name='DirectMessage',
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
