# Generated by Django 6.0.7 on 2026-09-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_activitylog'),
        ('users', '0010_alter_user_date_of_birth'),
    ]

    operations = [
    ]
