# Generated by Django 6.0.7 on 2026-09-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('customer_support', 'Customer Support'), ('buyer', 'Buyer'), ('artist', 'Artist'), ('hr', 'HR'), ('creative_moderator', 'Creative Moderator'), ('platform_admin', 'Platform Admin')], default='buyer', max_length=20),
        ),
    ]
