# Generated by Django 6.0.7 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_accepting_commissions",
            field=models.BooleanField(default=False),
        ),
    ]
