# Generated by Django 6.0.7 on 2026-09-21 13:40

import django.db.models.deletion
from django.db import migrations, models


def mark_existing_defaults(apps, schema_editor):
    apps.get_model('users', 'Address').objects.all().update(is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_local_role_and_remote_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='label',
            field=models.CharField(default='Home', max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.user'),
        ),
        migrations.RunPython(mark_existing_defaults, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='one_default_address_per_user'),
        ),
    ]
