# Generated by Django 6.0.7 on 2026-10-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_is_accepting_commissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commission_budget_note',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
