# Generated by Django 6.0.7 on 2026-10-01 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_commission_budget_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='commission_budget_note',
        ),
    ]
