# Generated by Django 6.0.7 on 2026-09-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_date_of_birth'),
        ('users', '0014_address_coordinates'),
    ]

    operations = [
    ]
