# Generated by Django 6.0.7 on 2026-10-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_commission_budget_note'),
        ('users', '0017_user_is_banned_user_suspended_until'),
    ]

    operations = [
    ]
