import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("artworks", "0006_artwork_edge_hash_artworksimilaritymatch_edge_hash_distance"), ("users", "0008_remove_usernotification_application_and_more")]
    operations = [
        migrations.CreateModel(name="WalletAccount", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("currency", models.CharField(default="PHP", max_length=3)), ("pending_balance", models.DecimalField(decimal_places=2, default=0, max_digits=12)), ("available_balance", models.DecimalField(decimal_places=2, default=0, max_digits=12)), ("paid_out_balance", models.DecimalField(decimal_places=2, default=0, max_digits=12)), ("updated_at", models.DateTimeField(auto_now=True)), ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="wallet", to="users.user"))]),
        migrations.CreateModel(name="PaymentSession", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("reference_id", models.CharField(max_length=64, unique=True)), ("gross_amount", models.DecimalField(decimal_places=2, max_digits=12)), ("platform_fee", models.DecimalField(decimal_places=2, max_digits=12)), ("artist_amount", models.DecimalField(decimal_places=2, max_digits=12)), ("xendit_session_id", models.CharField(blank=True, default="", max_length=80)), ("xendit_payment_id", models.CharField(blank=True, default="", max_length=80)), ("status", models.CharField(choices=[("pending", "Pending"), ("paid", "Paid"), ("expired", "Expired"), ("refunded", "Refunded")], default="pending", max_length=20)), ("paid_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("artist", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sales", to="users.user")), ("artwork", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payment_sessions", to="artworks.artwork")), ("buyer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchases", to="users.user"))]),
        migrations.CreateModel(name="WalletLedgerEntry", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("entry_type", models.CharField(choices=[("sale_held", "Sale held"), ("sale_available", "Sale available"), ("payout", "Payout"), ("refund_reversal", "Refund reversal")], max_length=30)), ("amount", models.DecimalField(decimal_places=2, max_digits=12)), ("created_at", models.DateTimeField(auto_now_add=True)), ("payment_session", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="wallets.paymentsession")), ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="entries", to="wallets.walletaccount"))], options={"ordering": ["-created_at"]}),
        migrations.AddConstraint(model_name="walletledgerentry", constraint=models.UniqueConstraint(fields=("payment_session", "entry_type"), name="unique_wallet_payment_entry")),
    ]
