# Generated by Django 6.0.7 on 2026-09-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_paymentsession_agreement_cancellationreturnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsession',
            name='artwork_png',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='checkout_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
