# Generated by Django 6.0.7 on 2026-09-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_paymentsession_artwork_png_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsession',
            name='is_simulated',
            field=models.BooleanField(default=False),
        ),
    ]
