# Generated by Django 6.0.7 on 2026-09-30 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0009_artwork_medium'),
        ('auctions', '0003_alter_auctionlisting_artist_and_more'),
        ('commissions', '0003_alter_commissionrequest_artist_and_more'),
        ('users', '0016_alter_user_date_of_birth'),
        ('wallets', '0004_paymentsession_is_simulated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern', models.CharField(max_length=60)),
                ('details', models.TextField(max_length=4000)),
                ('evidence', models.TextField(blank=True, max_length=2000)),
                ('image_data', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('awaiting_customer', 'Awaiting your reply'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='artworks.artwork')),
                ('auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auctions.auctionlisting')),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commissions.commissionrequest')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wallets.paymentsession')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='users.user')),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SupportReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='wallets.supportticket')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
