# Generated by Django 6.0.7 on 2026-09-30 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_is_banned_user_suspended_until'),
        ('wallets', '0005_supportticket_supportreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationreturnrequest',
            name='request_type',
            field=models.CharField(choices=[('refund', 'Refund'), ('cancellation', 'Cancellation'), ('return', 'Return')], max_length=20),
        ),
        migrations.CreateModel(
            name='DriverApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=80)),
                ('vehicle_details', models.CharField(max_length=500)),
                ('license_image', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('review_note', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='driver_application', to='users.user')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_driver_applications', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='AccountModerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('suspend', 'Suspend'), ('ban', 'Ban'), ('restore', 'Restore access')], max_length=12)),
                ('duration_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reason', models.TextField(max_length=4000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('review_note', models.TextField(blank=True, max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_account_actions', to='users.user')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_account_actions', to='users.user')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_moderation_requests', to='users.user')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_requests', to='wallets.supportticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('target',), name='one_pending_account_action')],
            },
        ),
    ]
