# Generated by Django 6.0.7 on 2026-10-03 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_commission_budget_note'),
        ('wallets', '0005_paymentsession_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationreturnrequest',
            name='counterpart_decision',
            field=models.CharField(default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='cancellationreturnrequest',
            name='counterpart_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cancellationreturnrequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancellationreturnrequest',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_request_responses', to='users.user'),
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='incident', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('evidence', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='open', max_length=20)),
                ('resolution', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incident_reports', to='wallets.paymentsession')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_received', to='users.user')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_reports', to='users.user')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_reviewed', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='AccountActionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=12)),
                ('reason', models.TextField()),
                ('duration_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=12)),
                ('review_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_account_actions', to='users.user')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_account_actions', to='users.user')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_action_requests', to='users.user')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_actions', to='wallets.incidentreport')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('target',), name='one_pending_account_action')],
            },
        ),
    ]
