# Generated by Django 6.0.7 on 2026-10-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_paymentsession_verification_code'),
        ('wallets', '0006_alter_cancellationreturnrequest_request_type_and_more'),
    ]

    operations = [
    ]
