# Generated by Django 6.0.7 on 2026-10-03 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_commission_budget_note'),
        ('wallets', '0006_cancellationreturnrequest_counterpart_decision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('refund', 'Refund'), ('wallet_credit', 'Wallet credit')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='authorized', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_authorizations_given', to='users.user')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_authorizations', to='wallets.paymentsession')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_authorizations_received', to='users.user')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_authorizations', to='wallets.incidentreport')),
            ],
        ),
    ]
