# Generated by Django 6.0.7 on 2026-10-03 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_financialauthorization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content_type', models.CharField(max_length=100)),
                ('content', models.BinaryField()),
                ('size', models.PositiveIntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='wallets.incidentreport')),
            ],
        ),
    ]
