# Generated by Django 6.0.7 on 2026-10-03 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_reportattachment'),
        ('wallets', '0009_support_assignment'),
    ]

    operations = [
    ]
