# Generated by Django 6.0.7 on 2026-10-03 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_20261002_2300'),
        ('wallets', '0009_support_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='reported_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_reports', to='users.user'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='reported_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
