# Generated by Django 6.0.7 on 2026-10-03 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_20261002_2300'),
        ('wallets', '0010_merge_0008_reportattachment_0009_support_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountactionrequest',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accountactionrequest',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountactionrequest',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_report_restrictions', to='users.user'),
        ),
        migrations.AddField(
            model_name='accountmoderationrequest',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accountmoderationrequest',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountmoderationrequest',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_ticket_restrictions', to='users.user'),
        ),
        migrations.AlterField(
            model_name='reportattachment',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='wallets.incidentreport'),
        ),
        migrations.CreateModel(
            name='RestrictionAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=10)),
                ('restriction_id', models.PositiveIntegerField()),
                ('explanation', models.TextField()),
                ('links', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('recommendation', models.CharField(blank=True, max_length=20)),
                ('moderator_note', models.TextField(blank=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_restriction_appeals', to='users.user')),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recommended_restriction_appeals', to='users.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restriction_appeals', to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='reportattachment',
            name='appeal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='wallets.restrictionappeal'),
        ),
        migrations.AddConstraint(
            model_name='restrictionappeal',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'recommended'])), fields=('user', 'source', 'restriction_id'), name='one_open_restriction_appeal'),
        ),
    ]
