# Generated by Django 6.0.7 on 2026-10-04 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0011_accountactionrequest_reversal_reason_and_more'),
        ('wallets', '0012_reconcile_incident_account_constraint'),
    ]

    operations = [
    ]
